name: cdk

on:
  release:
    types:
      - created

jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Upgrade npm
        run: npm install -g npm@7.8.0 && npm --version

      - name: Setup dependencies
        run: npm ci

      - name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}